name: Buildx

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-20.04
    outputs:
      builds: ${{ steps.builds.outputs.builds }}
      matrix: ${{ steps.builds.outputs.matrix }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - id: builds
        run: node ./images/build.js

      - if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: builds
          message: |
            # Builds
            ```json
            ${{ toJSON(fromJSON(steps.builds.outputs.builds).*.id) }}
            ```

  docker-build:
    needs:
      - docker
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{ fromJSON(needs.docker.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: cacheKeys
        env:
          KEYS: ${{ toJSON(matrix.cache.restoreKeys) }}
        run: |
          echo "::set-output name=entries::$(echo $KEYS | jq -cr '. | map("${{ runner.os }}-" + .) + ["${{ runner.os }}-"]')"

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.cache.path }}
          key: ${{ runner.os }}-buildx-${{ matrix.cache.cacheKey }}-${{ github.sha }}
          restore-keys: ${{ join(steps.cacheKeys.outputs.entries, '\n') }}

      - uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.buildx.context }}
          file: ${{ matrix.buildx.file }}
          build-args: ${{ matrix.buildx.buildArgs }}
          paltforms: ${{ matrix.buildx.paltforms }}
          pull: true,
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }},
          cache-from: ${{ matrix.buildx.cacheFrom }}
          cache-to: ${{ matrix.buildx.cacheTo }}
          tags: ${{ matrix.buildx.tags }}
